### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by nathanhruby** [sensu-plugins/sensu-plugins-graylog#3]
Hi Folks!

I have a few questions as I look at this plugin to monitor a new graylog 2.2 install

- I don't see a huge reason for the python scripts, is there a technical reason for them?  I'd be interested in porting them to ruby to reduce surface area.
- Due to proxy/LB issues I have my API/transport mounted on the same port as the front end, therefore API calls are mounted at "proto://host:port/api/" -- This corresponds with the "rest_transport_uri" setting.  I'd like to add a path prefix setting to allow for this.
- I don't see any support for using [Access Tokens](http://docs.graylog.org/en/2.1/pages/configuration/rest_api.html#creating-and-using-access-token) instead of username/password.  I would like to add this support.
- The metrics scripts only monitor a few metrics from the now available huge pile.  I haven't looked though to see what would be most useful but generally capturing more metrics is better than capturing less.  Any reason not to spit out most everything?

Are these changes things the maintainers would be interested in seeing?

Thanks!

-n

**Comment by eheydrick** [comment]
Hi! There's no reason the checks have to be python and porting to ruby would be fine as long as the ruby provides at least the same functionality and output as the python. Your other proposed changes look reasonable including collecting more metrics.

**Comment by nathanhruby** [comment]
Sounds great, thanks!  I hope to have some PR's later next week.
