### ISSUE TITLE
Add ability to specify connection protocol

### ISSUE THREAD

**Issue by fsuste** [sensu-plugins/sensu-plugins-graylog#8]
In every call of
```ruby
RestClient::Resource.new
```
The protocol is fixed to http, this is a problem since I can't force it to use https. I can send you a PR sometime during the week if you agree with me that this needs to be fixed.

**Comment by majormoses** [comment]
Nice, look forward to reviewing.

**Comment by jothoma1** [comment]
Nice! really need it. We are in full https and we cant use this check
Is it possible to add this option to check-graylog2-alive.rb too ?

**Comment by majormoses** [comment]
I looked and it would be trivial to add this to that script as well. I have not heard from the author of the PR in a while. If I don't hear back soon I will try to find the time on a weekend to fixup what I asked in the review and add it to that script as well.

**Comment by jothoma1** [comment]
@majormoses Thanks a lot in advance !!

**Comment by majormoses** [comment]
No problem ping me in a week if you don't hear back. Keeping track of all the things across ~200 plugins in my free time is difficult.

**Comment by majormoses** [comment]
I have updated the PR but as I don't really use graylog I'd prefer waiting on someone to test it for me before merging and releasing.

**Comment by jothoma1** [comment]
@majormoses Thanks !
I have tested the check-graylog2-alive.rb
But i have an SSL error (my certificate is ok)

Here is what i did :

> /opt/sensu/embedded/bin/ruby /opt/sensu/embedded/bin/check-graylog2-alive.rb -u admin -s https -p mypassword -P 9000 -h mygrayloghost
CheckGraylog2Alive UNKNOWN: SSL_connect returned=1 errno=0 state=error: certificate verify failed

**Comment by majormoses** [comment]
Hmm that would seem to indicate that your OS does not see your root CA or that the embedded ruby does not have that CA. We have I think 2 options:
- either allow specifying the SSL cert (something some of the plugins support I believe)
- configure the OS / ruby install to honor the cert

Here is an old post on unverified SSL certs in ruby.

**Comment by majormoses** [comment]
Another option is to add an option for disabling cert verification.

**Comment by jothoma1** [comment]
@majormoses Thanks for your work, can you add such an option ? (dont see the old post you mentioned)

**Comment by majormoses** [comment]
Woops forgot to include the link, pretty sure this is the one I looked at: https://mislav.net/2013/07/ruby-openssl I can work on adding it when I have some time (maybe this weekend).

**Comment by majormoses** [comment]
Post demonstrating how to install the certs into your OS: https://gemfury.com/help/could-not-verify-ssl-certificate/#updating-ssl-certificates

**Comment by majormoses** [comment]
@jothoma1 I have added the `insecure` option which aligns functionality wise with `curl`. Let me know how your testing goes. If all goes well I would like to get that merged and maybe we can collaborate on getting a better solution in as using `:insecure` is basically the same as not running TLS anyways but I would rather limit the change as much as possible right now and look to add new feature and deprecate this option in the future.

https://github.com/rest-client/rest-client#ssltls-support

**Comment by jothoma1** [comment]
@majormoses Thanks
Just tried the check-graylog2-alive.rb with the insecure option.
No more SSL error but now i think its a check problem :

```
> CheckGraylog2Alive UNKNOWN: 784: unexpected token at '<!DOCTYPE html>
> <html>
>   <head>
>     <meta http-equiv="X-UA-Compatible" content="IE=edge">
>     <meta name="robots" content="noindex, nofollow">
>     <meta charset="UTF-8">
>     <title>Graylog Web Interface</title>
>     <link rel="shortcut icon" href="/assets/favicon.png">
> 
>   </head>
```

**Comment by majormoses** [comment]
Hmm I can't see why that change would have broken this, I wonder if it is a version problem. Is there any way you could spin up the version of graylog you have locally without TLS and see if the same problem exists? If so could you try it with the current latest release and report back?

**Comment by majormoses** [comment]
Hmm you are correct I am able to successfully retrieve the data with curl but not with the check:
```
$ curl -s -S -u babrams:$(cat creds) https://graylog.<DOMAIN>.<TLD>/api/system | jq .
{
  "facility": "graylog-server",
  "codename": "Stiegl",
  "node_id": "c3f7185d-2fd3-4ad4-b3ae-f16c761f2be6",
  "cluster_id": "2efcc7ca-9bb4-4df8-968f-1a4a077f9397",
  "version": "2.2.3+7adc951",
  "started_at": "2018-01-12T05:39:26.396Z",
  "hostname": "MGMT-1.youcallmd.com",
  "lifecycle": "running",
  "lb_status": "alive",
  "timezone": "America/Los_Angeles",
  "operating_system": "Linux 4.4.0-109-generic",
  "is_processing": true
}
```

```
$ bundle exec ./bin/check-graylog2-alive.rb --protocol https --host graylog.<HOST>.<TLD> --username babrams --password $(cat creds) --port 443
CheckGraylog2Alive UNKNOWN: 784: unexpected token at '<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="robots" content="noindex, nofollow">
    <meta charset="UTF-8">
    <title>Graylog Web Interface</title>
    <link rel="shortcut icon" href="/assets/favicon.png">
    
  </head>
  <body>
    <script src="/config.js"></script>
    <script src="/assets/vendor.js"></script>
    
    <script src="/assets/polyfill.35e28e4da7743596569a.js"></script>
    
    <script src="/assets/plugin/org.graylog.plugins.pipelineprocessor.ProcessorPlugin/plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.0cbe11128085ed745b77.js"></script>
    
    <script src="/assets/plugin/org.graylog.plugins.map.MapWidgetPlugin/plugin.org.graylog.plugins.map.MapWidgetPlugin.5011f2ebff35ef956f1b.js"></script>
    
    <script src="/assets/plugin/org.graylog.plugins.enterprise_integration.EnterpriseIntegrationPlugin/plugin.org.graylog.plugins.enterprise_integration.EnterpriseIntegrationPlugin.3e5ff59c400f972516bd.js"></script>
    
    <script src="/assets/plugin/org.graylog.plugins.collector.CollectorPlugin/plugin.org.graylog.plugins.collector.CollectorPlugin.13edb0af11e27a17b001.js"></script>
    
    <script src="/assets/app.35e28e4da7743596569a.js"></script>
    
  </body>
</html>
'
```

**Comment by majormoses** [comment]
OK I figured it out, it was that `--apipath` defaults to an empty string. if you specify `/api` it works.
```
$ bundle exec ./bin/check-graylog2-alive.rb --protocol https --host graylog.<DOMAIN>.<TLD> --username babrams --password $(cat creds) --port 443 --apipath /api
CheckGraylog2Alive OK: Graylog2 server is: running/true/alive
```

This feels like a poor default. After we confirm this is working and merge the PR associated I will make a minor release and then change the default to be sane in a major release.

**Comment by majormoses** [comment]
fixed via  #9 and released in https://rubygems.org/gems/sensu-plugins-graylog/versions/1.3.0

**Comment by majormoses** [comment]
Addressing the issue with defaults in #10

**Comment by majormoses** [comment]
@jothoma1 I have released: https://rubygems.org/gems/sensu-plugins-graylog/versions/1.3.1 which should work for you with the options you previously supplied.

**Comment by jothoma1** [comment]
@majormoses Thanks a lot !
